Quiz/Quiz/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'static_pages/about'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/index', to: 'users#index'
  get '/dashboard', to: 'users#home'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/admin/users', to: 'admins#showusers'
  get '/admin/addadmin', to: 'admins#new'
  post 'admin/addadmin', to: 'admins#create'
  get 'admin/dashboard', to: 'admins#home'
  get 'admin/display', to: 'admins#display'
  delete 'admin/admins', to: 'admins#destroy'
  delete 'admin/users', to: 'users#destroy'

  get '/quiz', to: 'games#new'
  get '/quest/:id1/:id2', to: 'games#quest'
  post '/quest/:id1/:id2', to: 'games#updatequest'
  post '/updategame', to: 'games#update'

  resources :users
  resources :admins

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Quiz/Quiz/app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
   has_secure_password
   validates :password, presence: true, length: { minimum: 6 }
   has_many :games
end

Quiz/Quiz/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end
  def show
  	@user = User.find(params[:id])
  end
  def create
  	@user = User.new(user_params)
  	if @user.save
  		session[:user_id] = @user.id
  		redirect_to dashboard_path
  	else
  		render 'new'
  	end
  end
  def home
    @user = User.find(session[:user_id])
    render 'dashboard'
  end
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to admin_dashboard_path
  end

end

Quiz/Quiz/app/helpers/users_helper.rb
module UsersHelper
end

Quiz/Quiz/app/views/users/dashboard.html.erb
<h1>Welcome, <%= @user.name %>!</h1>
<%= link_to "Play Quiz!", quiz_path%>
<%= link_to "Logout", logout_path%>

Quiz/Quiz/app/views/users/display.html.erb
<h1>Users: </h1>
<% @user.each do |f| %>
<li><%= f[:email] %></li>
<% end %>

Quiz/Quiz/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<br>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:user, url: signup_path) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <br />

      <%= f.label :email %>
      <%= f.email_field :email %>
      <br />

      <%= f.label :password %>
      <%= f.password_field :password %>
      <br />

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
      <br />

      <%= f.submit "Create my account", class: "btn btn-primary" %>
      <br />
      <p>Already have an account? <%= link_to "Login", login_path %></p>
    <% end %>
  </div>
</div>
<%= link_to "Quiz Home", root_path %>

Quiz/Quiz/app/views/users/show.html.erb
<%= @user.name %>, <%=@user.email %>
<br>
<%= link_to "Logout", logout_path%>