Quiz/Quiz/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'static_pages/about'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/index', to: 'users#index'
  get '/dashboard', to: 'users#home'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/admin/users', to: 'admins#showusers'
  get '/admin/addadmin', to: 'admins#new'
  post 'admin/addadmin', to: 'admins#create'
  get 'admin/dashboard', to: 'admins#home'
  get 'admin/display', to: 'admins#display'
  delete 'admin/admins', to: 'admins#destroy'
  delete 'admin/users', to: 'users#destroy'

  get '/quiz', to: 'games#new'
  get '/quest/:id1/:id2', to: 'games#quest'
  post '/quest/:id1/:id2', to: 'games#updatequest'
  post '/updategame', to: 'games#update'

  resources :users
  resources :admins

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Quiz/Quiz/app/views/admins/display.html.erb
<h1>Admins : </h1>
<ul>
	<% @admins.each do |admin| %>
		<li>
			<%= admin.email %> ->
		  	<%= link_to "delete", admin, method: :delete, data: { confirm: "Are you sure?" } %>
		</li>
	<% end %>
</ul>
<%= link_to "Home", admin_dashboard_path %>

Quiz/Quiz/app/views/admins/home.html.erb
<h1>Admin Home</h1>
<ul>
	<li><%= link_to "Display Users", admin_users_path %></li>
	<li><%= link_to "Add User", signup_path %></li>
	<li><%= link_to "Add Admin", admin_addadmin_path %></li>
	<li><%= link_to "Display Admins", admin_display_path  %></li>
</ul>
<%= link_to "Quiz Home", root_path %>

Quiz/Quiz/app/views/admins/new.html.erb
<% provide(:title, 'Add Admin') %>
<h1>Add Admins</h1>

<% if @admin.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@admin.errors.count, "error") %>.
    </div>
    <ul>
    <% @admin.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<br>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:admin, url: admin_addadmin_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email %>
      <br />

      <%= f.label :password %>
      <%= f.password_field :password %>
      <br />

      <%= f.submit "Create admin account", class: "btn btn-primary" %>
      <br />
    <% end %>
  </div>
</div>
<br>
<%= link_to "Home", admin_dashboard_path %>

Quiz/Quiz/app/views/admins/show.html.erb
<h1>Welcome Admin</h1>
<%=@admin.email %>
<%= link_to "Dashboard", admin_dashboard_path %>
<br>

Quiz/Quiz/app/views/admins/showusers.html.erb
<ul>
	<% @users.each do |user| %>
		<li>
		  	<%= link_to user.name, user %>
		    <%= link_to "delete", user, method: :delete, data: { confirm: "Are you sure?" } %>
		</li>
	<% end %>
</ul>
<%= link_to "Home", admin_dashboard_path %>