Quiz/Quiz/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'static_pages/about'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/index', to: 'users#index'
  get '/dashboard', to: 'users#home'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/admin/users', to: 'admins#showusers'
  get '/admin/addadmin', to: 'admins#new'
  post 'admin/addadmin', to: 'admins#create'
  get 'admin/dashboard', to: 'admins#home'
  get 'admin/display', to: 'admins#display'
  delete 'admin/admins', to: 'admins#destroy'
  delete 'admin/users', to: 'users#destroy'

  get '/quiz', to: 'games#new'
  get '/quest/:id1/:id2', to: 'games#quest'
  post '/quest/:id1/:id2', to: 'games#updatequest'
  post '/updategame', to: 'games#update'

  resources :users
  resources :admins

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Quiz/Quiz/app/models/game.rb
class Game < ApplicationRecord
	belongs_to :user
end

Quiz/Quiz/app/controllers/games_controller.rb
class GamesController < ApplicationController
	def new
		if not session[:user_id].nil?
			@user = User.find(session[:user_id])
			puts @user.games.where(category: "Entertainment", subcat: "Books").first.nil?
			render 'new'
		else
			redirect_to login_path, :alert => "You must be logged in!"
		end
	end
	def update
		@user = User.find(session[:user_id])
		new_choice = params[:new]
		cont_choice = params[:cont]
		tmp = rand(155)
		if cont_choice.nil?
			if new_choice == 'newa'
				if @user.games.where(category: "Science", subcat: "Computers").first.nil?
					@user.games.create(user_id: session[:id],category: "Science", subcat: "Computers", state: "1", curr: 0, highest: 0)
				end
				@user.games.where(category: "Science", subcat: "Computers").first.update(state: "#{tmp}")
				@user.games.where(category: "Science", subcat: "Computers").first.update(curr: 0)
				redirect_to :action => 'quest', :id1 => 'Science', :id2 => 'Computers'
			elsif new_choice == 'newb'
				if @user.games.where(category: "Science", subcat: "Nature").first.nil?
					@user.games.create(user_id: session[:id],category: "Science", subcat: "Nature", state: "1", curr: 0, highest: 0)
				end
				@user.games.where(category: "Science", subcat: "Nature").first.update(state: "#{tmp}")
				@user.games.where(category: "Science", subcat: "Nature").first.update(curr: 0)
				redirect_to :action => 'quest', :id1 => 'Science', :id2 => 'Nature'
			elsif new_choice == 'newc'
				if @user.games.where(category: "Entertainment", subcat: "Television").first.nil?
					@user.games.create(user_id: session[:id],category: "Entertainment", subcat: "Television", state: "1", curr: 0, highest: 0)
				end
				@user.games.where(category: "Entertainment", subcat: "Television").first.update(state: "#{tmp}")
				@user.games.where(category: "Entertainment", subcat: "Television").first.update(curr: 0)
				redirect_to :action => 'quest', :id1 => 'Entertainment', :id2 => 'Television'
			elsif new_choice == 'newd'
				if @user.games.where(category: "Entertainment", subcat: "Books").first.nil?
					@user.games.create(user_id: session[:id],category: "Entertainment", subcat: "Books", state: "1", curr: 0, highest: 0)
				end
				@user.games.where(category: "Entertainment", subcat: "Books").first.update(state: "#{tmp}")
				@user.games.where(category: "Entertainment", subcat: "Books").first.update(curr: 0)
				redirect_to :action => 'quest', :id1 => 'Entertainment', :id2 => 'Books'
			elsif new_choice == 'newe'
				if @user.games.where(category: "Entertainment", subcat: "Music").first.nil?
					@user.games.create(user_id: session[:id],category: "Entertainment", subcat: "Music", state: "1", curr: 0, highest: 0)
				end
				@user.games.where(category: "Entertainment", subcat: "Music").first.update(state: "#{tmp}")
				@user.games.where(category: "Entertainment", subcat: "Music").first.update(curr: 0)
				redirect_to :action => 'quest', :id1 => 'Entertainment', :id2 => 'Music'
			end
		else
			if cont_choice == 'conta'
				@user.games.where(category: "Science", subcat: "Computers").first.update(curr: 0)
				redirect_to :action => 'quest', :id1 => 'Science', :id2 => 'Computers'
			elsif cont_choice == 'contb'
				@user.games.where(category: "Science", subcat: "Nature").first.update(curr: 0)
				redirect_to :action => 'quest', :id1 => 'Science', :id2 => 'Nature'
			elsif cont_choice == 'contc'
				@user.games.where(category: "Entertainment", subcat: "Television").first.update(curr: 0)
				redirect_to :action => 'quest', :id1 => 'Entertainment', :id2 => 'Television'
			elsif cont_choice == 'contd'
				@user.games.where(category: "Entertainment", subcat: "Books").first.update(curr: 0)
				redirect_to :action => 'quest', :id1 => 'Entertainment', :id2 => 'Books'
			elsif cont_choice == 'conte'
				@user.games.where(category: "Entertainment", subcat: "Music").first.update(curr: 0)
				redirect_to :action => 'quest', :id1 => 'Entertainment', :id2 => 'Music'
			end
		end
	end
	def quest
		@user = User.find(session[:user_id])
		start = @user.games.where(category: request[:id1], subcat: request[:id2]).first.state.to_i
		@questi = Question.where(category: request[:id1], subcat: request[:id2]).offset(start).first
		render 'question'
	end
	def updatequest
		@user = User.find(session[:user_id])
		@ugame = @user.games.where(category: request[:id1], subcat: request[:id2]).first
		start = @ugame.state.to_i
		@questi = Question.where(category: request[:id1], subcat: request[:id2]).offset(start).first
		puts params[:choice]
		puts "ANSWERS!!!"
		puts @questi.answer
		if params[:choice] == @questi.answer
			curr_score = @ugame.curr
			@ugame.update(curr: curr_score + 1)
			newstart = ((start + 1) % 155).to_s
			@ugame.update(state: newstart)
			# @ugame.saves
			redirect_to :action => 'quest', :id1 => request[:id1], :id2 => request[:id2]
		else
			max = if (@ugame.curr > @ugame.highest) then @ugame.curr else @ugame.highest end
			@ugame.update(highest: max)
			render 'incorrect'
		end
	end
end

Quiz/Quiz/app/helpers/games_helper.rb
module GamesHelper
end

Quiz/Quiz/app/views/games/incorrect.html.erb
<h2>Game Over!</h2>
<h3>Current Score : <%= @ugame.curr %></h3>
<%= link_to "Dashboard", dashboard_path %>

Quiz/Quiz/app/views/games/new.html.erb
<h1>Quiz</h1>
<%= form_for(:game, url: updategame_path) do |f| %>
	<table>
		<tr>
			<th>Category</th>
			<th>Sub-Category</th>
			<th>Current</th>
			<th>Highest</th>
			<th colspan="2">Game State</th>
		</tr>
		<tr>
			<td>Science</td>
			<td>Computers</td>
			<td>
				<% if not @user.games.where(category: "Science", subcat: "Computers").first.nil? %>
					<%= @user.games.where(category: "Science", subcat: "Computers").first.curr %>
				<% else %>
					<%= "-" %>
				<% end %>
			</td>
			<td>
				<% if not @user.games.where(category: "Science", subcat: "Computers").first.nil? %>
					<%= @user.games.where(category: "Science", subcat: "Computers").first.highest %>
				<% else %>
					<%= "-" %>
				<% end %>
			</td>
			<td><button name = 'new', value = "newa", type = "submit" >New Game</button></td>
			<td><button name = 'cont', value = "conta", type = "submit", 
			<% if @user.games.where(category: "Science", subcat: "Computers").first.nil? %>
				<%= "disabled" %>
			<% end %>
			>Continue</button></td>
			<td></td>
		</tr>
		<tr>
			<td>Science</td>
			<td>Nature</td>
			<td>
				<% if not @user.games.where(category: "Science", subcat: "Nature").first.nil? %>
					<%= @user.games.where(category: "Science", subcat: "Nature").first.curr %>
				<% else %>
					<%= "-" %>
				<% end %>
				</td>
			<td>
				<% if not @user.games.where(category: "Science", subcat: "Nature").first.nil? %>
					<%= @user.games.where(category: "Science", subcat: "Nature").first.highest %>
				<% else %>
					<%= "-" %>
				<% end %>
			</td>
			<td><button name = 'new', value = "newb", type = "submit" >New Game</button></td>
			<td><button name = 'cont', value = "contb", type = "submit", 
			<% if @user.games.where(category: "Science", subcat: "Nature").first.nil? %>
				<%= "disabled" %>
			<% end %>
			>Continue</button></td>
		</tr>
		<tr>
			<td>Entertainment</td>
			<td>Television</td>
			<td>
				<% if not @user.games.where(category: "Entertainment", subcat: "Television").first.nil? %>
					<%= @user.games.where(category: "Entertainment", subcat: "Television").first.curr %>
				<% else %>
					<%= "-" %>
				<% end %>
			</td>
			<td><% if not @user.games.where(category: "Entertainment", subcat: "Television").first.nil? %>
					<%= @user.games.where(category: "Entertainment", subcat: "Television").first.highest %>
				<% else %>
					<%= "-" %>
				<% end %>
			</td>
			<td><button name = 'new', value = "newc", type = "submit" >New Game</button></td>
			<td><button name = 'cont', value = "contc", type = "submit", 
			<% if @user.games.where(category: "Entertainment", subcat: "Television").first.nil? %>
				<%= "disabled" %>
			<% end %>
			>Continue</button></td>
		</tr>
		<tr>
			<td>Entertainment</td>
			<td>Books</td>
			<td>
				<% if not @user.games.where(category: "Entertainment", subcat: "Books").first.nil? %>
					<% @user.games.where(category: "Entertainment", subcat: "Books").first.curr %>
				<% else %>
					<%= "-" %>
				<% end %>
			</td>
			<td>
				<% if not @user.games.where(category: "Entertainment", subcat: "Books").first.nil? %>
					<%= @user.games.where(category: "Entertainment", subcat: "Books").first.highest %>
				<% else %>
					<%= "-" %>
				<% end %>
			</td>
			<td><button name = 'new', value = "newd", type = "submit" >New Game</button></td>
			<td><button name = 'cont', value = "contd", type = "submit", 
			<% if @user.games.where(category: "Entertainment", subcat: "Books").first.nil? %>
				<%= "disabled" %>
			<% end %>
			>Continue</button></td>
		</tr>
		<tr>
			<td>Entertainment</td>
			<td>Music</td>
			<td>
				<% if not @user.games.where(category: "Entertainment", subcat: "Music").first.nil? %>
					<%= @user.games.where(category: "Entertainment", subcat: "Music").first.curr %>
				<% else %>
					<%= "-" %>
				<% end %>
			</td>
			<td>
				<% if not @user.games.where(category: "Entertainment", subcat: "Music").first.nil? %>
					<%= @user.games.where(category: "Entertainment", subcat: "Music").first.highest %>
				<% else %>
					<%= "-" %>
				<% end %>
			</td>
			<td><button name = 'new', value = "newe", type = "submit" >New Game</button></td>
			<td><button name = 'cont', value = "conte", type = "submit", 
			<% if @user.games.where(category: "Entertainment", subcat: "Music").first.nil? %>
				<%= "disabled" %>
			<% end %>
			>Continue</button></td>
		</tr>
	</table>
<% end %>

<%= link_to "Home", dashboard_path %>

Quiz/Quiz/app/views/games/question.html.erb
<h2>Question : </h2>
<p>Q. <%= Nokogiri::HTML.parse("#{@questi.question}").text %> </p>
<% temp = rand(4) %>
<div>
	<%= form_tag("/quest/#{@questi.category}/#{@questi.subcat}", method: "post") %>
		<ul>
			<% 4.times do |f| %>
				<% if temp == 0 %>
					<input type="radio" name="choice" value = "<%= @questi.option1 %>"><%= Nokogiri::HTML.parse("#{@questi.option1}").text %><br>
				<% elsif temp == 1 %>
					<input type="radio" name="choice" value = "<%= @questi.option2 %>"><%= Nokogiri::HTML.parse("#{@questi.option2}").text %><br>
				<% elsif temp == 2 %>
					<input type="radio" name="choice" value = "<%= @questi.option3 %>"><%= Nokogiri::HTML.parse("#{@questi.option3}").text %><br>
				<% else %>
					<input type="radio" name="choice" value = "<%= @questi.option4 %>"><%= Nokogiri::HTML.parse("#{@questi.option4}").text %><br>
				<% end %>
				<% temp = (temp + 1) % 4 %>
			<% end %>
		</ul>
		<input type="Submit" name="Submit">
</div>

<%= link_to "Dashboard", dashboard_path %>